### ISSUE TITLE
Offset argument to place chord Symbol in a more precise location inside a word

### ISSUE THREAD

**Issue by rousbound** [ljgago/typst-chords#1]
I think it would be useful to have a parameter that you can use to control where the chord is inside the word. 

For example, supposing the chord on the word "misfortune" lands on the the last syllable "ne", I would want to place the chord symbol with an offset, so it lands on the right-most side of the word.

I know it is hard to calculate syllables and stuff, so a straightforward implementation would be to use a length parameter to off set the chord symbol, like: 

#chord[misfortune][G] [0.2cm]

**Comment by ljgago** [comment]
Hi, you can do this:

misfortu#chord[ne][G]

But this has a problem, when the chord name is long, the canvas above the syllable splits the word.

Is good your idea with the offset.

**Comment by rousbound** [comment]
> Hi, you can do this:
> 
> misfortu#chord[ne][G]
> 
> But this has a problem, when the chord name is long, the canvas above the syllable splits the word.
> 
> Is good your idea with the offset.

Maybe an even better API would be to pass in the number of letters you want to offset. 

If typst has a way to measure the size of the letters(in current font and size) it will work.

This should be better because you would only need to count the letters and the result would be right without needing to adjust it.

Not sure if it's possible

**Comment by rousbound** [comment]
I think this is possible doing something along the lines of:
```typst

#let position_in_word(word, index) = {
  style( styles => {
   let sum 
    for i in range(4) {
      sum += measure(word.at(i), styles).width
    }
    let letter = word.at(index)
    [Position of letter #letter in #word is #sum]
  }
  )
}

#position_in_word("Hello World!", 6)

```

Then you would only need to place the chord relative to the word using the offset provided.

Not sure how to do that though.

**Comment by ljgago** [comment]
I did tests, but the `style` function has a strange behavior (https://github.com/typst/typst/issues/766) and I can't get the measure value.
Also I tried to use the typst-canvas functions inside of `style` function but didn't work.

I keep on investigating.

**Comment by ljgago** [comment]
Now is possible to set an offset to position the chord above a specific character of the word, 

Example:

```js
#chord[hello][C][2] //  C chord above "e" character
#chord[hello][C][] // C chord centered above word
```

Also, the first character of the chord name is centered with the target character of the word.

**Comment by debnath-d** [comment]
Unless I'm missing something, currently there is no way to write chords in cases where the chord should be played before (or after) the word, for example (from https://tabs.ultimate-guitar.com/tab/green-day/boulevard-of-broken-dreams-chords-146744):

```
Fm        G#                D#             A#              Fm
 I walk a lonely road, the only one that I have ever known
           G#              D#                A#               Fm
Don't know where it goes, but it's home to me and I walk alone
```

or multiple chords before lyrics:

```
[Interlude]

(Fm) G#  D#           A#             Fm
           I walk alone, I walk alone
(Fm) G#  D#           A#
           I walk alone, I walk a....
```

Currently the offset parameter does not make use of 0 (or negative values). I think the first issue can be solved by placing the chord *before* the beginning of a word when 0 is provided as the offset. For a word of length n, an offset greater than n should place the chord just *after* the the word, in cases where a chord has to be played after the word.

For the second issue of placing chords without lyrics, simply allowing empty first parameter should solve the problem:

```
(Fm) G#  D#           A#             Fm
           I walk alone, I walk alone

                    |
                    | should become
                    v

#chord[][Fm][] #chord[][G#][] #chord[I][D#][0] walk #chord[alone][D#][4], I walk #chord[alone][Fm][6]
```

**Comment by ljgago** [comment]
Hi @debnath-d!
This PR https://github.com/ljgago/typst-chords/pull/18 addresses the first case by using index 0 to place the chord before the word, but this functionality has not yet been released.

Currently, you can emulate all of these functions using the whitespace character `~`.

First case:
```typ
Fm        G#                D#             A#              Fm
 I walk a lonely road, the only one that I have ever known

#chord[~~I][Fm][1] walk a #chord[lonely][C\#][1] road, the #chord[only][D\#][] one that I #chord[have][A\#][] ever known ~ #chord[~][Fm][]
```
Second case:

```typ
(Fm) G#  D#           A#             Fm
           I walk alone, I walk alone

#chord[~][Fm][] ~ #chord[~][G\#][] ~ #chord[~~I][D\#][1] walk #chord[alone][D\#][4], I walk #chord[alone][Fm][6]
```

**Comment by debnath-d** [comment]
> Currently, you can emulate all of these functions using the whitespace character `~`.

I wasn't aware that `~` can be used as whitespace. That's what I was missing. Got it now, thanks!

Perhaps a good idea would be to mention this somewhere in the documentation, possibly with an example. This will avoid confusion for future users of this package.
